name: datalens
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - pandas
  - jupyter
  - sqlalchemy
  - psycopg2
  - geopandas
  - pip:
    - dash
    - dash-bootstrap-components
    - flask-caching
    - tqdm
    - waitress
    - traval
    - pastas
    - pastastore
    - hydropandas
    - icecream
    - i18nice[YAML]
    - arcticdb
