[project]
authors = ["Davíd Brakenhoff <d.brakenhoff@artesia-water.nl>"]
channels = ["conda-forge"]
description = "Environment for GW DataLens"
name = "datalens"
platforms = ["linux-64"]
version = "0.2.1"

[tasks]
editable_install = { cmd = "pip install -e ../hydropandas && pip install -e ../pastas && pip install -e ../pastastore && pip install -e ../traval && pip install -e .", description = "Install all packages in editable mode." }
gwdatalens = "gwdatalens"

[dependencies]
geopandas = "*"
jupyter = "*"
llvmlite = "*"
matplotlib = "*"
numpy = "<2.0"
pandas = "*"
pip = "*"
psycopg2 = "*"
python = "3.11.*"
sqlalchemy = "*"

[pypi-dependencies]
arcticdb = "*"
dash = "*"
dash-bootstrap-components = "*"
flask-caching = "*"
i18nice = { version = "*", extras = ["YAML"] }
icecream = "*"
tqdm = "*"
waitress = "*"
gwdatalens = "*"
# hydropandas = { path = "../hydropandas", editable = true }
# pastas = { path = "../pastas", editable = true }
# pastastore = { path = "../pastastore", editable = true }
# traval = { path = "../traval", editable = true }
# gwdatalens = { path = ".", editable = true }
