[settings]
DEBUG = true
LOCALE = "en"
DJANGO_APP = false           # set to True to run under Django application
BACKGROUND_CALLBACKS = false # false is recommended
SERIES_LOAD_LIMIT = 10       # number of observations to load and plot simultaneously

[pastastore]
name = "zeeland_bro"
path = "/home/david/github/gws_qc/traval_scripts/pastasdb/" # path to pastas model database
